### ISSUE TITLE
少了三个库要怎么添加呢

### ISSUE THREAD

**Issue by janus-xiao** [xxzzddxzd/unitySpeedTools#2]
CoreGraphics、QuartzCore、libsubstrate,这三个库没有可以去那里下载呢.

**Comment by anjiuzhe** [comment]
你下载下来能编译吗？我的下载下来签名配置项都没有了

**Comment by janus-xiao** [comment]
> 你下载下来能编译吗？我的下载下来签名配置项都没有

**Comment by janus-xiao** [comment]
> 你下载下来能编译吗？我的下载下来签名配置项都没有了

编译失败，没搞成功

**Comment by anjiuzhe** [comment]
> 

我也是额，iOS这块还有没其他的加速方法呢
