### ISSUE TITLE
大佬好，有个问题，现在fgo国服更新了版本，加速器不适用了...

### ISSUE THREAD

**Issue by coke9960** [xxzzddxzd/unitySpeedTools#8]
之前还可以用，估计是fgo更新了unity的版本，用不了了，不知道您还会更新不？以前在你店里买过来加速器来着，要是看到了麻烦回复一下呗，不行也告诉我一下，麻烦你了@xxzzddxzd

**Comment by xxzzddxzd** [comment]
这个免费版的用不了吗

**Comment by coke9960** [comment]
> 

用不了了，我是用的更新后的版本，也就是21年那个版本，在版本更新前还可以用，现在就不行了。
具体情况是打开游戏没有那个加速框了，即使通过其他插件卡出来加速小圆钮了，点上去也一直提示在初始化中。
机子版本是IOS13.4.1，se2
估计是fgo更新了unity版本还是啥？

**Comment by coke9960** [comment]
> 这个免费版的用不了吗

用不了了，我是用的更新后的版本，也就是21年那个版本，在版本更新前还可以用，现在就不行了。
具体情况是打开游戏没有那个加速框了，即使通过其他插件卡出来加速小圆钮了，点上去也一直提示在初始化中。
机子版本是IOS13.4.1，se2
估计是fgo更新了unity版本还是啥？

**Comment by coke9960** [comment]
> 这个免费版的用不了吗

大佬，请问您还打算更新不？没有催更的意思，就是您要打算更新的话，我就留个念想等，没有这个打算的话我就用模拟器了。感谢您的付出！

**Comment by xxzzddxzd** [comment]
> > 这个免费版的用不了吗
> 
> 大佬，请问您还打算更新不？没有催更的意思，就是您要打算更新的话，我就留个念想等，没有这个打算的话我就用模拟器了。感谢您的付出！

我抽时间看看

**Comment by coke9960** [comment]
> > > 这个免费版的用不了吗
> > 
> > 
> > 大佬，请问您还打算更新不？没有催更的意思，就是您要打算更新的话，我就留个念想等，没有这个打算的话我就用模拟器了。感谢您的付出！
> 
> 我抽时间看看

好的，谢谢您！

**Comment by xxzzddxzd** [comment]
> > > > 这个免费版的用不了吗
> > > 
> > > 
> > > 大佬，请问您还打算更新不？没有催更的意思，就是您要打算更新的话，我就留个念想等，没有这个打算的话我就用模拟器了。感谢您的付出！
> > 
> > 
> > 我抽时间看看
> 
> 好的，谢谢您！

这个有越狱检测？我打开闪退

**Comment by coke9960** [comment]
> > > > > 这个免费版的用不了吗
> > > > 
> > > > 
> > > > 大佬，请问您还打算更新不？没有催更的意思，就是您要打算更新的话，我就留个念想等，没有这个打算的话我就用模拟器了。感谢您的付出！
> > > 
> > > 
> > > 我抽时间看看
> > 
> > 
> > 好的，谢谢您！
> 
> 这个有越狱检测？我打开闪退

没有的吧？我这边不会的，我的机子是se2,ios13.4，用的奥德赛越狱和slieo，没有安装任何屏蔽越狱插件，正常打开不闪退的。
不好意思哦，刚没看到

**Comment by xxzzddxzd** [comment]
> > > > > > 这个免费版的用不了吗
> > > > > 
> > > > > 
> > > > > 大佬，请问您还打算更新不？没有催更的意思，就是您要打算更新的话，我就留个念想等，没有这个打算的话我就用模拟器了。感谢您的付出！
> > > > 
> > > > 
> > > > 我抽时间看看
> > > 
> > > 
> > > 好的，谢谢您！
> > 
> > 
> > 这个有越狱检测？我打开闪退
> 
> 没有的吧？我这边不会的，我的机子是se2,ios13.4，用的奥德赛越狱和slieo，没有安装任何屏蔽越狱插件，正常打开不闪退的。 不好意思哦，刚没看到

我试了下能加速

**Comment by coke9960** [comment]
> > > > > > > 这个免费版的用不了吗
> > > > > > 
> > > > > > 
> > > > > > 大佬，请问您还打算更新不？没有催更的意思，就是您要打算更新的话，我就留个念想等，没有这个打算的话我就用模拟器了。感谢您的付出！
> > > > > 
> > > > > 
> > > > > 我抽时间看看
> > > > 
> > > > 
> > > > 好的，谢谢您！
> > > 
> > > 
> > > 这个有越狱检测？我打开闪退
> > 
> > 
> > 没有的吧？我这边不会的，我的机子是se2,ios13.4，用的奥德赛越狱和slieo，没有安装任何屏蔽越狱插件，正常打开不闪退的。 不好意思哦，刚没看到
> 
> 我试了下能加速

啊？我不行啊？我重新下载了游戏也不行的？您下载的是2.67.0的国服版本fgo吗？或者您需要我录个像啥的不？

**Comment by xxzzddxzd** [comment]
> > > > > > > > 这个免费版的用不了吗
> > > > > > > 
> > > > > > > 
> > > > > > > 大佬，请问您还打算更新不？没有催更的意思，就是您要打算更新的话，我就留个念想等，没有这个打算的话我就用模拟器了。感谢您的付出！
> > > > > > 
> > > > > > 
> > > > > > 我抽时间看看
> > > > > 
> > > > > 
> > > > > 好的，谢谢您！
> > > > 
> > > > 
> > > > 这个有越狱检测？我打开闪退
> > > 
> > > 
> > > 没有的吧？我这边不会的，我的机子是se2,ios13.4，用的奥德赛越狱和slieo，没有安装任何屏蔽越狱插件，正常打开不闪退的。 不好意思哦，刚没看到
> > 
> > 
> > 我试了下能加速
> 
> 啊？我不行啊？我重新下载了游戏也不行的？您下载的是2.67.0的国服版本fgo吗？或者您需要我录个像啥的不？

2.67.0
